name: Testes Java

on:

  # Permite executar manualmente pela aba Actions
  workflow_dispatch:

  # Executa quando for criado ou atualizado
  # um Pull Request para a master
  pull_request:
    
       

  # Executa quando houver push na master
  # incluindo um merge
  push:
    
       


jobs:

  testes:

    # Máquina virtual fornecida pelo GitHub
    runs-on: ubuntu-latest

    steps:

      # Baixa o código do repositório
      - name: Baixar codigo
        uses: actions/checkout@v4

      # Instala/configura o Java
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Executa os testes unitários
      - name: Executar testes
        run: mvn test
